apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# first install console add/ons
  - console/dev-view.yaml
  - console/links.yaml

# install all operators
  - operators/gitops.yaml
  - operators/pipelines.yaml
  - operators/serverless.yaml
  - operators/crunchy.yaml
  
# configure registry
  - registry/image-registry.yaml
  - registry/config.yaml

